### ISSUE TITLE
Trojan:Script/Wacatac.B!ml Detected by Microsoft Defender Antivirus

### ISSUE THREAD

**Issue by YBS-PC** [gSpotx2f/packages-openwrt#2]
![++](https://github.com/gSpotx2f/packages-openwrt/assets/52429295/5632f904-6201-43fc-90a6-af4ae8bf0199)
same as 1.3.0

**Comment by gSpotx2f** [comment]
Microsoft machine learning bullshit. Just google it.
https://forums.lenovo.com/t5/Security-Malware/Recovery-Media-VIRUS-detected/m-p/5214185?page=1#5935658
https://www.reddit.com/r/antivirus/comments/168l15k/comment/keljptr/
https://answers.microsoft.com/ru-ru/windows/forum/all/%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D0%B5/2292e6cd-7548-447c-8616-1210cf39a283
