### ISSUE TITLE
Suggestion for luci-app-disks-info application

### ISSUE THREAD

**Issue by ZMJGMADHPXWT** [gSpotx2f/packages-openwrt#3]
Hello and thank you for your apps, they are really helpful!
I'd like to suggest an additional functions for luci-app-disks-info application.
1) Add critical SMART values to database constantly. Database is stored in the RAM. User can specify delays between SMART checks.
1	Raw Read Error Rate
5	Reallocated Sector Ct
10	Spin Retry Count
196	Reallocated Event Count
197	Current Pending Sector
199	UDMA CRC Error Count

2) Add an option to save that database to USB drive to avoid data loose during reboots. Also user can specify for how long that data could be stored. Like 1 day, 1 month, 2 years.

3) It would be nice to have an option to see these values as graph. To understand how SMART values were changing during specified period of time. Like 1 day, 1 month, 2 years.

4) And the most important - alerting. I'd like to be able to run bash scripts when critical values are changing. Like to send an email or Telegram message. 

Thanks in advance.

**Comment by gSpotx2f** [comment]
Hello! luci-app-disks-info is a simple app that just displays smartctl output. I don't plan to make it more complicated for now.
